### ISSUE TITLE
[use help]

### ISSUE THREAD

**Issue by CnKyo** [LecleVietnam/LeclePackageIssue#14]
hello,i used custom videoStyle property like this 
videoStyle: VideoStyle(
                play: Icon(Icons.play_arrow_rounded),
                pause: Icon(Icons.pause),
                fullscreen: Icon(Icons.fullscreen_exit_outlined),
                playedColor: Colors.lightBlue,
              ),
,i had try reboot and reloading but is not working too,  please tell me hao to set it,thank you so much!

**Comment by LecleVietnam** [comment]
Hi @CnKyo,
Thank you for your feedback, our team will check this issue and we will let you know when we are done.

**Comment by LecleVietnam** [comment]
Hi @CnKyo,
We have checked your issue and we found that your issue is caused because you are using the old yoyo_player package and our team has migrated it to lecle_yoyo_player package. Could you please change the package to our team package [here](https://pub.dev/packages/lecle_yoyo_player) and let us know if there is any issue? Thank you.

This is an example of using VideoStyle in our package:
```dart
VideoStyle(
   playIcon: Icon(Icons.play_arrow_rounded, color: Colors.lightBlue),
   pauseIcon: Icon(Icons.pause),
   fullscreenIcon: Icon(Icons.fullscreen_exit_outlined, color: Colors.blue),
)
```

**Comment by CnKyo** [comment]
ok,I see. Thank you very much for your answer
